config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :designs
  resources :sides
  resources :artifacts do
    member do
      get 'copy_props'
    end
  end
  resources :properties

  scope '/manage' do
    resources :users
  end

  root 'badges#new'

  resources :badges do
    member do
      get 'camera'    # takes image
      get 'print'     # prints badge
      get 'generate'  # generate badge

      patch 'snapshot'  # uploads file
      get 'crop'      # crops picture
      post 'snapshot' # uploads snapshot
    end
  end

  post 'lookup' => 'badges#lookup', as: :lookup
end

app/models/badge.rb
require 'ldap_helper'
include LdapHelper

class Badge < ApplicationRecord

  has_attached_file :picture, styles: { badge: "300x400>", thumb: ["96x96#", :png] }, processors: [:cropper]
  has_attached_file :card, styles: { preview: { geometry: "318x200>", format: :png, convert_options: "-png" } }, processors: [:pdftoppm]

  default_scope { order(created_at: :desc) }

  attr_accessor :crop_x, :crop_y, :crop_h, :crop_w

  validates_attachment :picture, content_type: { content_type: ["image/jpeg", "image/png"] }
  validates_attachment :card, content_type: { content_type: "application/pdf" }

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :department, presence: true
  validates :title, presence: true
  validates :employee_id, presence: true

  def cropping?
    return !crop_x.blank?
  end

  def picture_geometry(style = :original)
    @geometry ||= {}
    @geometry[style] ||= Paperclip::Geometry.from_file(picture.path(style))
  end

  def self.ad_lookup(attribute, value)
    entry = nil

    if ENV["USE_LDAP"] == "true"
      with_ldap do |ldap|
        results = ldap.search(
          filter: "(#{attribute}=#{value})",      # active_filter,
          attributes: %w(givenname mail dn sn employeeID manager title department thumbnailPhoto) )
        Rails.logger.debug("#{results.size} results found")
        if results.size == 1
          entry = results.first
        end
      end
    end

    entry
  end

  # must populate dn for ad thumbnail to be updated
  def self.lookup_employee(attribute, value)
    info = {}

    if ENV["USE_LDAP"] == "true"
      Rails.logger.debug("using ldap employee lookup")

      entry = ad_lookup(attribute, value)
      unless entry.blank?
        info = {
          first_name: entry.givenname.first,
          last_name:  entry.sn.first,
          department: entry.department.first,
          title: entry.title.first,
          employee_id: entry.employeeid.first,
          dn: entry.dn
        }
        # write current ad thumbnail photo to tmp dir
        # File.open("/tmp/adthumb-#{entry.employeeid.first}", "wb") do |file|
        #   entry.thumbnailPhoto.each do |b|
        #     file.write b
        #   end
        # end
      end
    else
      Rails.logger.debug("no employee lookup defined")
    end

    info
  end

  def name
    "#{first_name} #{last_name}"
  end

  def update_ad_thumbnail
    return if ENV["USE_LDAP"] != "true" || dn.blank? || update_thumbnail == false

    with_ldap do |ldap|
      picture_data = File.binread(picture.path(:thumb))
      ldap.replace_attribute dn, :thumbnailPhoto, picture_data
      raise Exception, "Unable to update thumbnailPhoto - #{ldap.get_operation_result.message}" if ldap.get_operation_result.code != 0
    end
  end
end

app/controllers/badges_controller.rb
class BadgesController < ApplicationController
  #before_action :set_badge, only: [:show, :edit, :update, :destroy, :camera, :print, :snapshot, :crop, :generate]
  load_and_authorize_resource except: :lookup

  # GET /badges
  # GET /badges.json
  def index
    @badges = Badge.paginate(page: params[:page])
  end

  # GET /badges/1
  # GET /badges/1.json
  def show
  end

  # GET /badges/new
  def new
    @badge = Badge.new
  end

  # GET /badges/1/edit
  def edit
  end

  # POST /badges
  # POST /badges.json
  def create
    @badge = Badge.new(badge_params)

    respond_to do |format|
      if @badge.save
        format.html { redirect_to camera_badge_url(@badge) }
        format.json { render :show, status: :created, location: @badge }
      else
        format.html { render :new }
        format.json { render json: @badge.errors, status: :unprocessable_entity }
      end
    end
  end

  # GET /badges/:id/camera
  # shows camera, allows taking of snapshot
  def camera
  end

  def generate
    begin
      Design.selected.render_card(@badge)
      flash[:notice] = "Card has been generated and is ready to print."
    rescue Exception => e
      flash[:error] = "Unable to generate card - #{e.message}"
    end
    redirect_to @badge
  end

  def print
    print_badge

    respond_to do |format|
      format.html { redirect_to @badge }
    end
  end

  # PATCH/PUT /badges/1
  # PATCH/PUT /badges/1.json
  def update
    respond_to do |format|
      if @badge.update(badge_params)
        format.html { redirect_to @badge, notice: 'Badge was successfully updated.' }
        format.json { render :show, status: :ok, location: @badge }
      else
        format.html { render :edit }
        format.json { render json: @badge.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /badges/1
  # DELETE /badges/1.json
  def destroy
    @badge.destroy
    respond_to do |format|
      format.html { redirect_to badges_url, notice: 'Badge was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  # GET /badges/1/crop
  def crop
    ratio = @badge.picture_geometry(:original).width / @badge.picture_geometry(:badge).width
    @badge.crop_x = params[:x].to_i * ratio
    @badge.crop_y = params[:y].to_i * ratio
    @badge.crop_w = params[:w].to_i * ratio
    @badge.crop_h = params[:h].to_i * ratio

    @badge.picture.reprocess! :badge
    @badge.picture.reprocess! :thumb

    begin
      @badge.update_ad_thumbnail
    rescue => e
      flash[:error] ||= []
      flash[:error] << e.message
    rescue Exception => e
      flash[:error] ||= []
      flash[:error] << e.message
    end

    begin
      if Design.selected.blank?
        flash[:error] ||= []
        flash[:error] << "No default design has been set."
      else
        Design.selected.render_card(@badge)
      end
    rescue Exception => e
      flash[:error] ||= []
      flash[:error] << "Unable to print card - #{e.message}"
    end

    if ENV["AUTO_PRINT"].blank? || ENV["AUTO_PRINT"] == "true"
      print_badge
    end

    respond_to do |format|
      # crop is posted via ajax so you cannot just redirect have to tell the browser to
      if ENV["AUTO_PRINT"].blank? || ENV["AUTO_PRINT"] == "true"
        format.html { render text: badges_url }
        format.json { render json: { url: badges_url } }
      else
        format.html { render text: badge_url(@badge) }
        format.json { render json: { url: badge_path(@badge) } }
      end
    end
  end

  # POST /snapshot
  def snapshot
    require 'rest-client'

    id = @badge.id

    if params[:badge].present? and params[:badge][:picture].present?
      # do it the paperclip way
      @badge.update(snapshot_params)
    else
      # do it the raw_post way from the jpeg_camera js
      File.open("/tmp/picture_#{id}.jpg", 'wb') do |f|
        f.write(request.raw_post)
      end
      @badge.picture =  File.open "/tmp/picture_#{id}.jpg"
      @badge.save!
      File.delete("/tmp/picture_#{id}.jpg") if File.exist?("/tmp/picture_#{id}.jpg")
    end

    response = RestClient.post "https://apicloud-facerect.p.mashape.com/process-file.json",
      { image: File.new(@badge.picture.path(:badge)) },
      { "X-Mashape-Key" => "DG3G8aFfsemshG7TRzYqz5f9FFPwp1BjRDejsncx9nQ6T06SW3" }

    # unirest is outdated and has security issues so replaced with rest-client
    # # # These code snippets use an open-source library. http://unirest.io/ruby
    # response = Unirest.post "https://apicloud-facerect.p.mashape.com/process-file.json",
    #   headers:{
    #     "X-Mashape-Key" => "DG3G8aFfsemshG7TRzYqz5f9FFPwp1BjRDejsncx9nQ6T06SW3"
    #   },
    #   parameters:{
    #     "image" => File.new(@badge.picture.path(:badge))
    #   }

    # JSON results:
    # {
    #   "faces": [
    #     {
    #       "orientation": "frontal",
    #       "x": 147,
    #       "y": 161,
    #       "width": 478,
    #       "height": 478,
    #       "features": {
    #         "eyes": [
    #           {
    #             "x": 277,
    #             "y": 309,
    #             "width": 62,
    #             "height": 62
    #           },
    #           {
    #             "x": 417,
    #             "y": 295,
    #             "width": 83,
    #             "height": 83
    #           }
    #         ],
    #         "nose": {
    #           "x": 350,
    #           "y": 406,
    #           "width": 76,
    #           "height": 64
    #         },
    #         "mouth": {
    #           "x": 319,
    #           "y": 481,
    #           "width": 146,
    #           "height": 88
    #         }
    #       }
    #     }
    #   ],
    #   "image": {
    #     "width": 800,
    #     "height": 800
    #   }
    # }

    results = JSON.parse(response)
    s = "handleSnapshotUploadResponse('" + { url: @badge.picture.url(:badge), results: results }.to_json.to_s + "');"

    respond_to do |format|
      format.html { render text: @badge.picture.url(:badge) }
      format.json { render json: { url: @badge.picture.url(:badge), results: results }, status: :ok }
      format.js { render js: s, status: :ok }
    end
  end

  def lookup
    # find, don't find, or error
    # use ldap or not
    errors = []
    begin
      info = Badge.lookup_employee("employeeId", params[:id])
    rescue => e
      errors << "#{e.class} #{e.message}"
    end

    respond_to do |format|
      if errors.blank?
        format.html { render :lookup, layout: false, locals: { info: info } }
        format.json { render json: info, status: :ok }
      else
        format.html { render text: "<div class='alert alert-danger'>#{errors.join(', ')}</div>" }
        format.json { render json: errors, status: :not_found }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_badge
      @badge = Badge.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def badge_params
      params.require(:badge).permit(:employee_id, :first_name, :last_name, :title, :department, :dn, :update_thumbnail)
    end

    def snapshot_params
      params.require(:badge).permit(:picture)
    end

    def print_badge
      if ENV["PRINTER"].blank?
        flash[:error] = "No printer defined in PRINTER environment variable."
      elsif @badge.card.blank?
        # there is no card so try to generate one
        begin
          Design.selected.render_card(@badge)
        rescue Exception => e
          flash[:error] = "Unable to generate card - #{e.message}"
        end
      end

      if flash[:error].blank?
        cmd = "lp -d #{ENV["PRINTER"]} #{ENV["PRINTER_OPTIONS"]} #{@badge.card.path(:original)} 2>&1"
        output = `#{cmd}`
        printed_ok =$?.success?
        Rails.logger.info "#{cmd} = #{printed_ok}"

        if printed_ok
          flash[:notice] = "Badge was sent to printer.  #{output}"
        else
          flash[:error] = "Unable to send badge to printer.  #{output}"
        end
      end
    end
end

app/helpers/badges_helper.rb
module BadgesHelper
end

app/views/badges/_form.html.haml
= simple_form_for @badge do |f|
  = f.error_notification
  = f.input :first_name, options
  = f.input :last_name, options
  = f.input :department, options
  = f.input :title, options
  = f.input :employee_id, { label: 'Employee ID' }.merge(options)
  - if ENV["USE_LDAP"] == "true"
    = f.input :update_thumbnail, { label: 'Update the photo in Active Directory so that it shows up in Outlook, Helpdesk applications, and SharePoint?' }.merge(checkbox_options)
  = f.hidden_field :dn, label: 'AD Distinguished Name', title: 'required for updating thumbnail in AD'
  = f.button :submit, "Next >", class: 'btn btn-primary', data: { disable_with: "Working..." } if @badge.new_record?

app/views/badges/_steps.html.haml
.steps-bar
  %ul.steps
    %li.step-enter{class: "step#{step == 1 ? '-active' : ''}"}
      .item
        Lookup or Enter Details
      .arrow-right
    %li.step-take{class: "step#{step == 2 ? '-active' : ''}"}
      .arrow-in
      .item
        Take Picture
      .arrow-right
    %li.step-crop{class: "step#{step == 3 ? '-active' : ''}"}
      .arrow-in
      .item
        Crop Picture
      .arrow-right
    %li.step-print{class: "step#{step == 4 ? '-active' : ''}"}
      .arrow-in
      .item
        Print Badge

app/views/badges/camera.html.haml
%h1 New Badge
.row
  = render partial: 'steps', locals: { step: 2 }
.row
  .col-xs-12.col-sm-4
    = render partial: 'form', locals: { badge: @badge,
      options: { input_html: { readonly: :readonly } },
      checkbox_options: { input_html: { disabled: :disabled } } }
  .col-xs-12.col-sm-4
    #camerabox
      #camera
      .status
      %button.btn.btn-primary.take-snapshot{ onclick: "takeSnapshot()" } Take
      %button.btn.btn-default.retake-snapshot.hidden{ onclick: "discardSnapshot()" } Retake
      %button.btn.btn-primary.use-snapshot.hidden{ onclick: "useSnapshot()", data: { url: snapshot_badge_url(@badge, format: :json) } } Use
      = simple_form_for(:badge, url: snapshot_badge_url(@badge.id, format: :js), data: { remote: true }, html: { class: 'form-inline upload-pic'}) do |f|
        = f.input :picture, as: :file, label: false
        %button.btn.btn-default Upload
      #upload_response
    #cropbox.hidden
      %img
      .status
      %button.btn.btn-primary.retake2-snapshot.hidden{ onclick: "discardSnapshot()" } Retake
      %button.btn.btn-primary.crop-snapshot.hidden{ onclick: "cropSnapshot()", data: { url: crop_badge_url(@badge, format: :json), disable_with: 'Working...' }}
        - if ENV["AUTO_PRINT"].blank? || ENV["AUTO_PRINT"] == "true"
          Crop & Print
        - else
          Crop

%script
  $(document).ready(startCamera);
  $(document).on('page:load', startCamera);

app/views/badges/index.html.haml
%h1 Badges

%table.table.table-striped
  %thead
    %tr
      %th Employee Id
      %th Name
      %th Title
      %th Department
      %th Created
      - if ENV["USE_LDAP"] == "true"
        %th{title: 'Active Directory thumbnail updated?'} AD
      %th
  %tbody
    - @badges.each do |badge|
      %tr
        %td
          = badge.employee_id
          - if badge.picture.blank?
            %span.label.label-warning.label-as-badge
              no photo
          - elsif badge.card.blank?
            %span.label.label-warning.label-as-badge
              no card
        %td= link_to badge.name, badge
        %td= badge.title
        %td= badge.department
        %td= l(badge.created_at.localtime, format: :short)
        - if ENV["USE_LDAP"] == "true"
          %td= (badge.update_thumbnail.blank? || badge.update_thumbnail == false ? '' : 'Y')
        %td
          = link_to 'Delete', badge, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-xs btn-danger' if !current_user.nil? && current_user.has_role?(:admin)

= will_paginate @badges, renderer: BootstrapPagination::Rails

.form-actions
  = link_to 'New Badge', new_badge_path, class: 'btn btn-default'

app/views/badges/lookup.html.haml
- if info[:name].nil?
  .alert.alert-warning Employee not found

app/views/badges/new.html.haml
%h1 New Badge
.row
  = render partial: 'steps', locals: { step: 1 }
.row
  .col-xs-12
    - if @badge.new_record?
      .lookup-form
        = simple_form_for :lookup, url: lookup_url(format: :json), remote: true, html: { class: "form-inline lookup-form" } do
          .form-group
            %label{for: "employee_id"} Employee ID
            %input.form-control.required{type: "text", name: "id", id: "employee_id"}
            %button.btn.btn-default.lookup-employee{ "data-disable-with": "<i class=\"fa fa-spin fa-spinner\"></i> Looking...".html_safe }
              %i.fa.fa-search
              Lookup
        .lookup-status
    = render partial: 'form', locals: { badge: @badge, options: {}, checkbox_options: {} }

app/views/badges/photo.html.erb
<h1>New Badge</h1>

<div class="row">
  <div class="col-xs-6 col-sm-4">
    <%= simple_form_for @badge do |f| %>
      <%= f.input :name, input_html: { readonly: :readonly } %>
      <%= f.input :department, input_html: { readonly: :readonly } %>
      <%= f.input :title, input_html: { readonly: :readonly } %>
      <%= f.input :employee_id, label: 'Employee ID', input_html: { readonly: :readonly } %>
    <% end %>
  </div>
  <div class="col-xs-6 col-sm-4">
    <div id="camera"></div>
    <button class="btn btn-primary take-snapshot" onclick="takeSnapshot()">Take</button>
    <button class="btn btn-default discard-snapshot hidden" onclick="discardSnapshot()">Retry</button>
    <button class="btn btn-primary use-snapshot hidden" onclick="useSnapshot()">Use</button>
    <div id="upload_response"></div>
  </div>
</div>
<%= link_to "Print", print_badge_url(@badge, remote: true), class: 'btn btn-primary' %>

<script>
  $(document).ready(startCamera);
  $(document).on('page:load', startCamera);
</script>

app/views/badges/show.html.haml
%h1 Badge

.row
  .col-xs-6.col-sm-5
    = render partial: 'form', locals: { badge: @badge, 
      options: { input_html: { readonly: :readonly } }, 
      checkbox_options: { input_html: { disabled: :disabled } } }
  .col-xs-6.col-sm-5
    - unless @badge.card.blank?
      .card-preview
        %img{src: @badge.card.url(:preview)}

.form-actions
  = link_to print_badge_url(@badge), class: 'btn btn-primary' do
    %i.fa.fa-printer
    Print
  - if current_user.has_role?(:admin)
    = link_to generate_badge_url(@badge), class: 'btn btn-default generate-badge' do
      %i.fa.fa-refresh
      Generate

  = link_to 'List Badges', badges_path, class: 'btn btn-default'