config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :designs
  resources :sides
  resources :artifacts do
    member do
      get 'copy_props'
    end
  end
  resources :properties

  scope '/manage' do
    resources :users
  end

  root 'badges#new'

  resources :badges do
    member do
      get 'camera'    # takes image
      get 'print'     # prints badge
      get 'generate'  # generate badge

      patch 'snapshot'  # uploads file
      get 'crop'      # crops picture
      post 'snapshot' # uploads snapshot
    end
  end

  post 'lookup' => 'badges#lookup', as: :lookup
end

app/models/property.rb
class Property < ApplicationRecord
  belongs_to :artifact

  ALLOWED = [
    "align",
    "at",
    "bottom",
    "center",
    "color",
    "color1",
    "color2",
    "down",
    "final_gap",
    "fit",
    "from",
    "height",
    "left",
    "overflow",
    "position",
    "right",
    "rotate",
    "size",
    "style",
    "to",
    "top",
    "up",
    "valign",
    "vposition",
    "width"
  ].freeze

  default_scope { order( { artifact_id: :asc, name: :asc } ) }

  validates :name, presence: true

end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  #before_action :set_property, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource # from cancancan

  # GET /properties
  # GET /properties.json
  def index
    @properties = Property.paginate(page: params[:page])
  end

  # GET /properties/1
  # GET /properties/1.json
  def show
  end

  # GET /properties/new
  def new
    @property = Property.new
  end

  # GET /properties/1/edit
  def edit
  end

  # POST /properties
  # POST /properties.json
  def create
    @property = Property.new(property_params)

    respond_to do |format|
      if @property.save
        format.html { redirect_to @property, notice: 'Property was successfully created.' }
        format.json { render :show, status: :created, location: @property }
      else
        format.html { render :new }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /properties/1
  # PATCH/PUT /properties/1.json
  def update
    respond_to do |format|
      if @property.update(property_params)
        format.html { redirect_to @property, notice: 'Property was successfully updated.' }
        format.json { render :show, status: :ok, location: @property }
      else
        format.html { render :edit }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /properties/1
  # DELETE /properties/1.json
  def destroy
    @property.destroy
    respond_to do |format|
      format.html { redirect_to properties_url, notice: 'Property was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_property
      @property = Property.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def property_params
      params.require(:property).permit(:artifact_id, :name, :value)
    end
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/views/properties/_form.html.haml
= simple_form_for(@property) do |f|
  = f.error_notification
  
  .form-inputs
    = f.association :artifact, wrapper_html: { class: 'col-xs-4' }
    = f.input :name, wrapper_html: { class: 'col-xs-4' }
    = f.input :value, wrapper_html: { class: 'col-xs-4' }

  .form-actions
    = f.button :submit, class: 'btn btn-default'
    = content_for :buttons

app/views/properties/edit.html.haml
%h1 Editing Property

- content_for :buttons do
  = link_to 'Show', @property, class: 'btn btn-default'
  = link_to 'Back', properties_path, class: 'btn btn-default'

= render 'form'

app/views/properties/index.html.haml
%h1 Listing Properties

%table.table.table-striped
  %thead
    %tr
      %th Artifact
      %th Name
      %th Value
      %th
  %tbody
    - @properties.each do |property|
      %tr
        %td= property.artifact.description
        %td= link_to property.name, edit_property_path(property)
        %td= property.value
        %td
          = link_to 'Delete', property, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-xs btn-danger'

= will_paginate @properties, renderer: BootstrapPagination::Rails

.form-actions
  = link_to 'New Property', new_property_path, class: 'btn btn-default'
  = link_to 'Artifacts', artifacts_path, class: 'btn btn-default'

app/views/properties/new.html.haml
%h1 New Property

- content_for :buttons do
  = link_to 'Back', properties_path, class: "btn btn-default"

= render 'form'

app/views/properties/show.html.haml
%p
  %strong Artifact:
  = @property.artifact.description

%p
  %strong Name:
  = @property.name

%p
  %strong Value:
  = @property.value

.form-actions
  = link_to 'Edit', edit_property_path(@property), class: "btn btn-default"
  = link_to 'Back', properties_path, class: "btn btn-default"