config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :designs
  resources :sides
  resources :artifacts do
    member do
      get 'copy_props'
    end
  end
  resources :properties

  scope '/manage' do
    resources :users
  end

  root 'badges#new'

  resources :badges do
    member do
      get 'camera'    # takes image
      get 'print'     # prints badge
      get 'generate'  # generate badge

      patch 'snapshot'  # uploads file
      get 'crop'      # crops picture
      post 'snapshot' # uploads snapshot
    end
  end

  post 'lookup' => 'badges#lookup', as: :lookup
end

app/models/side.rb
class Side < ApplicationRecord
  SIDES = [{ name: 'Front', value: 0 }, { name: 'Back', value: 1 }].freeze
  ORIENTATIONS = [{ name: 'Portrait', value: 0 }, { name: 'Landscape', value: 1 }].freeze

  belongs_to :design
  has_many :artifacts, dependent: :destroy

  accepts_nested_attributes_for :artifacts, reject_if: :all_blank, allow_destroy: true

  validates :order, presence: true
  validates :orientation, presence: true
  validates :margin, presence: true
  validates :width, presence: true
  validates :height, presence: true

  def name
    "#{design.name} (#{side_name})"
  end

  def side_name
    SIDES.detect{ |s| s[:value] == order }[:name] rescue ""
  end

  def orientation_name
    ORIENTATIONS.detect{ |s| s[:value] == orientation }[:name] rescue ""
  end

  def reorder_artifacts
    i = 0
    artifacts.each do |artifact|
      i = i + 10
      # skip validations and callbacks and stamping
      artifact.update_columns(order: i) unless artifact.destroyed?
    end
  end
end

app/controllers/sides_controller.rb
class SidesController < ApplicationController
  #before_action :set_side, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource # from cancancan

  # GET /sides
  # GET /sides.json
  def index
    @sides = Side.paginate(page: params[:page])
  end

  # GET /sides/1
  # GET /sides/1.json
  def show
  end

  # GET /sides/new
  def new
    @side = Side.new
  end

  # GET /sides/1/edit
  def edit
  end

  # POST /sides
  # POST /sides.json
  def create
    @side = Side.new(side_params)

    respond_to do |format|
      if @side.save
        format.html { redirect_to @side, notice: 'Side was successfully created.' }
        format.json { render :show, status: :created, location: @side }
      else
        format.html { render :new }
        format.json { render json: @side.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sides/1
  # PATCH/PUT /sides/1.json
  def update
    respond_to do |format|
      if @side.update(side_params)
        format.html { redirect_to @side, notice: 'Side was successfully updated.' }
        format.json { render :show, status: :ok, location: @side }
      else
        format.html { render :edit }
        format.json { render json: @side.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sides/1
  # DELETE /sides/1.json
  def destroy
    @side.destroy
    respond_to do |format|
      format.html { redirect_to sides_url, notice: 'Side was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_side
      @side = Side.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def side_params
      params.require(:side).permit(:design_id, :order, :orientation, :margin, :width, :height,
        artifacts_attributes: [:id, :side_id, :name, :order, :description, :value, :_destroy])
    end
end

app/helpers/sides_helper.rb
module SidesHelper
end

app/views/sides/_artifact_details.html.haml
%h3 Artifacts
- if side.artifacts.blank?
  = link_to "No artifacts exist yet.  Click here to add some.", edit_side_url(side)
- else
  %table.table.table-striped.table-condensed
    %thead
      %tr
        %th Name
        %th Order
        %th Description
        %th Value
        %th Properties
    %tbody
      -side.artifacts.each do |a|
        %tr
          %td= link_to a.name, edit_artifact_path(a)
          %td= a.order
          %td= a.description
          %td= a.value
          %td
            - if a.properties.present?
              %ul.props
                - a.properties.each do |p|
                  %li
                    %span= "#{p.name}:"
                    = "#{p.value}"

app/views/sides/_artifact_fields.html.haml
.nested-fields.row
  = f.input :name, wrapper_html: { class: 'col-xs-2' }
  = f.input :order, wrapper_html: { class: 'col-xs-2' }
  = f.input :description, wrapper_html: { class: 'col-xs-3' }
  = f.input :value, wrapper_html: { class: 'col-xs-3' }
  %div.form-group.col-xs-2
    %br
    = link_to_remove_association "remove", f, class: 'btn btn-xs btn-danger'

app/views/sides/_details.html.haml
.row
  .col-sm-6
    %h1
      = link_to side.design do
        - if side.design.default == true
          %i.fa.fa-star{title: 'default design'}
        = "#{side.design.name} Design"
    %h2= link_to "#{side.side_name} Side", edit_side_path(side)
    %ul
      %li= "Orientation: #{side.orientation_name}"
      %li= "Margin: #{side.margin}"
      %li= "Width: #{side.width}"
      %li= "Height: #{side.height}"
  .col-sm-6
    - if side.design.sample.blank? || !File.exist?(side.design.sample.path(:preview))
      No preview available
    - else
      .card-preview=image_tag side.design.sample.url(:preview)

app/views/sides/_form.html.erb
<%= simple_form_for(@side) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.association :design, include_blank: false, wrapper_html: { class: 'col-xs-12' } %>
    <%= f.input :order, collection: Side::SIDES.map {|s| [ s[:name], s[:value] ]}, 
      include_blank: false, wrapper_html: { class: 'col-xs-3' } %>
    <%= f.input :orientation, collection: Side::ORIENTATIONS.map {|s| [ s[:name], s[:value] ]}, 
      include_blank: false, wrapper_html: { class: 'col-xs-3' } %>
    <%= f.input :margin, wrapper_html: { class: 'col-xs-2' } %>
    <%= f.input :width, wrapper_html: { class: 'col-xs-2' } %>
    <%= f.input :height, wrapper_html: { class: 'col-xs-2' } %>
  </div>

  <h2>Artifacts</h2>
  <div id="artifacts">
    <%= f.simple_fields_for :artifacts do |artifact| %>
      <%= render 'artifact_fields', f: artifact %>
    <% end %>
  </div>

  <div class="form-actions">
    <%= link_to_add_association 'Add Artifact', f, :artifacts, class: 'btn btn-default' %>
    <%= f.button :submit, class: 'btn btn-default' %>
    <%= content_for :buttons %>
  </div>
<% end %>

app/views/sides/edit.html.haml
%h1 Editing Side

- content_for :buttons do
  = link_to 'Show', @side, class: "btn btn-default"
  = link_to 'Back', sides_path, class: "btn btn-default"

= render 'form'

app/views/sides/index.html.haml
%h1 Sides

%table.table.table-striped
  %thead
    %tr
      %th Design
      %th Order
      %th Orientation
      %th Margin
      %th Width
      %th Height
      %th

  %tbody
    - @sides.each do |side|
      %tr
        %td= side.design.name
        %td= link_to side.side_name, side
        %td= side.orientation_name
        %td= side.margin
        %td= side.width
        %td= side.height
        %td
          = link_to 'Edit', edit_side_path(side), class: 'btn btn-xs btn-default'
          = link_to 'Delete', side, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-xs btn-danger'

= will_paginate @sides, renderer: BootstrapPagination::Rails

.form-buttons
  = link_to 'New Side', new_side_path, class: "btn btn-default" 
  = link_to 'Designs', designs_path, class: "btn btn-default"

app/views/sides/new.html.haml
%h1 New Side

- content_for :buttons do
  = link_to 'Back', sides_path, class: "btn btn-default"

= render 'form'

app/views/sides/show.html.haml
= render partial: 'details', locals: { side: @side }
= render partial: 'artifact_details', locals: { side: @side }

.form-actions
  = link_to 'Edit Side', edit_side_path(@side), class: "btn btn-default"
  = link_to 'Back', sides_path, class: "btn btn-default"