config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :designs
  resources :sides
  resources :artifacts do
    member do
      get 'copy_props'
    end
  end
  resources :properties

  scope '/manage' do
    resources :users
  end

  root 'badges#new'

  resources :badges do
    member do
      get 'camera'    # takes image
      get 'print'     # prints badge
      get 'generate'  # generate badge

      patch 'snapshot'  # uploads file
      get 'crop'      # crops picture
      post 'snapshot' # uploads snapshot
    end
  end

  post 'lookup' => 'badges#lookup', as: :lookup
end

app/models/artifact.rb
class Artifact < ApplicationRecord
  ALLOWED = [
    "layout_guides",
    "fill_gradient",
    "fill_rectangle",
    "font",
    "image",
    "move_down",
    "move_up",
    "text_box",
    "textbox"
  ].freeze

  belongs_to :side
  has_many :properties, dependent: :destroy

  has_attached_file :attachment

  default_scope { order( { side_id: :asc, order: :asc, name: :asc } ) }

  accepts_nested_attributes_for :properties, reject_if: :all_blank, allow_destroy: true

  validates :name, presence: true
  validates :order, presence: true
  # only attachment types that prawn can handle
  validates_attachment :attachment, content_type: { content_type: ["image/jpeg", "image/png", "application/x-font-ttf", "application/x-font-truetype"] }

  after_save :reorder
  after_destroy :reorder

  def reorder
    side.reorder_artifacts
  end

end

app/controllers/artifacts_controller.rb
class ArtifactsController < ApplicationController
  #before_action :set_artifact, only: [:show, :edit, :update, :destroy, :copy_props]
  load_and_authorize_resource # from cancancan

  # GET /artifacts
  # GET /artifacts.json
  def index
    @artifacts = Artifact.paginate(page: params[:page])
  end

  # GET /artifacts/1
  # GET /artifacts/1.json
  def show
  end

  # GET /artifacts/new
  def new
    @artifact = Artifact.new
  end

  # GET /artifacts/1/edit
  def edit
  end

  # POST /artifacts
  # POST /artifacts.json
  def create
    @artifact = Artifact.new(artifact_params)

    respond_to do |format|
      if @artifact.save
        format.html { redirect_to @artifact, notice: 'Artifact was successfully created.' }
        format.json { render :show, status: :created, location: @artifact }
      else
        format.html { render :new }
        format.json { render json: @artifact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /artifacts/1
  # PATCH/PUT /artifacts/1.json
  def update
    respond_to do |format|
      if @artifact.update(artifact_params)
        # to assist in designing cards, update the sample when an artifact is updated
        # TODO! check performance
        @artifact.side.design.render_card nil, false, true

        format.html { redirect_to @artifact.side, notice: 'Artifact was successfully updated.' }
        format.json { render :show, status: :ok, location: @artifact }
      else
        format.html { render :edit }
        format.json { render json: @artifact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /artifacts/1
  # DELETE /artifacts/1.json
  def destroy
    @artifact.destroy
    respond_to do |format|
      format.html { redirect_to artifacts_url, notice: 'Artifact was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  def copy_props
    prior = Artifact.where('side_id = :side and "order" < :order', side: @artifact.side_id, order: @artifact.order).last
    unless prior.blank?
      prior.properties.each do |property|
        @artifact.properties.build({name: property.name, value: property.value}) unless @artifact.properties.exists?(name: property.name)
      end
      @artifact.save
    end

    redirect_to artifacts_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_artifact
      @artifact = Artifact.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def artifact_params
      params.require(:artifact).permit(:side_id, :name, :order, :description, :value, :attachment,
        properties_attributes: [:id, :artifact_id, :name, :value, :_destroy])
    end
end

app/helpers/artifacts_helper.rb
module ArtifactsHelper
end

app/views/artifacts/_form.html.haml
= simple_form_for(@artifact) do |f|
  = f.error_notification

  .form-inputs
    = f.association :side, label_method: :name, wrapper_html: { class: 'col-xs-6 col-sm-4' }
    = f.input :order, wrapper_html: { class: 'col-xs-6 col-sm-2' }
    = f.input :name, wrapper_html: { class: 'col-xs-6 col-sm-2' }
    = f.input :value, wrapper_html: { class: 'col-xs-6 col-sm-4' }
    = f.input :description, wrapper_html: { class: 'col-xs-12' }
    = f.input :attachment, as: :file, wrapper_html: { class: 'col-xs-12' }

  .row
    .col-xs-12


  %h2 Properties
  #properties
    = f.simple_fields_for :properties do |property|
      = render 'property_fields', f: property

  .form-actions
    = link_to_add_association 'Add Property', f, :properties, class: 'btn btn-default'
    = f.button :submit, class: 'btn btn-default'
    = content_for :buttons

app/views/artifacts/_property_fields.html.haml
.nested-fields.row
  = f.input :name, wrapper_html: { class: 'col-xs-4' }
  = f.input :value, wrapper_html: { class: 'col-xs-4' }
  %div.col-xs-4
    %br
    = link_to_remove_association "remove", f, class: 'btn btn-xs btn-danger'

app/views/artifacts/edit.html.haml
%h1 Editing Artifact

- content_for :buttons do
  = link_to 'Show', @artifact, class: 'btn btn-default'
  = link_to 'Back', artifacts_path, class: 'btn btn-default'

= render 'form'

app/views/artifacts/index.html.haml
%h1 Artifacts

%table.table.table-striped
  %thead
    %tr
      %th Side
      %th Name
      %th Order
      %th Description
      %th Value
      %th Properties
      %th
  %tbody
    - @artifacts.each do |artifact|
      %tr
        %td= link_to artifact.side.name, artifact.side
        %td= link_to artifact.name, artifact
        %td= artifact.order
        %td= artifact.description
        %td= artifact.value
        %td
          %ul.props
            - artifact.properties.each do |p|
              %li= link_to "#{p.name}: #{p.value}", edit_property_path(p)
        %td
          = link_to 'Copy Prior Props', copy_props_artifact_path(artifact), class: 'btn btn-xs btn-default'
          = link_to "Edit", edit_artifact_path(artifact), class: 'btn btn-xs btn-default'
          = link_to 'Delete', artifact, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-xs btn-danger'

= will_paginate @artifacts, renderer: BootstrapPagination::Rails

.form-actions
  = link_to 'New Artifact', new_artifact_path, class: "btn btn-default"
  = link_to 'Sides', sides_path, class: "btn btn-default"
  = link_to 'Designs', designs_path, class: "btn btn-default"

app/views/artifacts/new.html.haml
%h1 New Artifact

- content_for :buttons do
  = link_to 'Back', artifacts_path, class: "btn btn-default"

= render 'form'

app/views/artifacts/show.html.haml
%p
  %strong Design:
  = link_to @artifact.side.design.name, @artifact.side.design

%p
  %strongSide:
  = link_to @artifact.side.side_name, @artifact.side

%p
  %strongName:
  = @artifact.name

%p
  %strongOrder:
  = @artifact.order

%p
  %strongDescription:
  = @artifact.description

%p
  %strongValue:
  = @artifact.value

%p
  %strongAttachement:
  = image_tag @artifact.attachment.url unless @artifact.attachment.blank?

%table.table.table-striped
  %thead
    %tr
      %th Name
      %th Value
  %tbody
    - @artifact.properties.each do |p|
      %tr
        %td= p.name
        %td= p.value

.form-actions
  = link_to 'Edit', edit_artifact_path(@artifact), class: "btn btn-default"
  = link_to 'New Property', new_property_path, class: "btn btn-default"
  = link_to 'Back', artifacts_path, class: "btn btn-default"